= Docker Gradle sample

This project uses 
the https://github.com/gesellix/gradle-docker-plugin[Gradle Docker plugin].
In the `buildSrc` directory is a custom Gradle plugin that creates
tasks and a custom extension to have a clean DSL to configure
the Docker images and containers in the project.

== Images

We need to apply the `DockerManagementPlugin` plugin in our project. This adds
the `buildImage` and `removeImage` tasks to create and remove a 
local Docker image. The sources are copied from `src/docker` and any
other custom location with the `prepareImage` task. The `buildImage`
task depends on this task.

The name of the image is defined in the `dockerConfiguration` extension
that is added by the `DockerManagementPlugin` plugin.

== Containers

To create a container and start a container we have the tasks
`createContainer` and `startContainer`. The name of the container
is defined in the `dockerConfiguration` extension.

To stop a container, run the `stopContainer` task and to remove it
we run `removeContainer`.

== Sample

This sample project create a Docker image based on `nginx` and with
custom content that is copied from `src/www`. In `build.gradle` we can
see how the `prepareImage` task is configured with the extra source dir.

With the following commands we create an image, container and start the container:

  $ ./gradlew buildImage createContainer startContainer
  
After the container is started we can open `http://localhost:9000/` in our web browser.
